name: cherry_components
description: Collection of fresh UI components.
version: 0.3.1+1
homepage: https://github.com/jesusrp98/cherry_components

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.1
  decorated_icon: ">=1.2.1 <2.0.0"
  expand_widget: ^3.1.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
