name: cherry_components
description: Collection of fresh UI components.
version: 0.3.1+1
homepage: https://github.com/jesusrp98/cherry_components

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  decorated_icon: ^1.2.1
  expand_widget: ^3.1.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
